### PR TITLE
Blog :Added blog post for everyone struggles

### PR DESCRIPTION
**Pull request by sandygudie**
Fixes Issue: https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA-en-blog/issues/59

Description
As part of the requirement from outreachy to write about "Everyone Struggles"

### CODE REVIEW

**Comment by sandygudie** [comment]
@RealRichi3, feel free to pull and add yours when you are ready

**Comment by RealRichi3** [comment]
Alright then

**Comment by RealRichi3** [comment]
@sandygudie the deploy log isn't working

**Comment by BatoolMM** [comment]
Thank you for creating the post, I submitted an issue to follow up with this error.

**Comment by BatoolMM** [comment]
@alswajiab and @melibleq would you be able to review this PR, please?

**Review by BatoolMM — APPROVED** [review]
Thank you, amazing as usual!

**Pull request merged**
