### PR TITLE
added aria-labels, removed inline css, updated style.css

### PR DESCRIPTION
**Pull request by vanithaak**
Summary
Improved web accessibilty

List of changes proposed in this PR (pull-request)
1. added aria-labels, in required places and changed a HTML tag (also indentation)
2.  removed inline css and added them to style.css

I also wanted to add a back-to-top button in the website, am I allowed to do that?  or should I make a first-time-issue @BatoolMM

### CODE REVIEW

**Comment by BatoolMM** [comment]
Thank you @vanithaak for your wonderful contribution!

Can you resolve the conflict and rebase the PR, please?
If you would like to add new changes, please create a new issue and PR!

**Comment by vanithaak** [comment]
@BatoolMM I never rebased a PR but, I did something. Can you please check

**Comment by BatoolMM** [comment]
Hi @vanithaak, thank you for your hard work. This blog is based on Quarto, so we the HTML files are generated from quarto files and we aren't supposed to change any of the HTML files because they'll be overwritten again. All files in `_site` shouldn't be changed. 

I am very sorry that this wasn't clear, you have worked very hard with fixing tags and inline CSS.

**Comment by okerekechinweotito** [comment]
@BatoolMM I see you triggered the Github-Action workflow.  Is the deploy-preview now working ?. 
Pls let me know so that I can decide whether to look for further solutions

**Comment by BatoolMM** [comment]
@okerekechinweotito I tagged you in https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA-en-blog/pull/25#issuecomment-1279699083.

I will close this PR for now but feel free to re-open it later. Thank you again @vanithaak for your work!

**Pull request closed without merging**
