### PR TITLE
[10/4/2023] fixed grid alignment bug

### PR DESCRIPTION
**Pull request by sandygudie**
PR DESCRIPTION
Fix for issue: https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA-en-blog/issues/61

### CODE REVIEW

**Comment by BatoolMM** [comment]
Hi @sandygudie, thank you - I am looking at this old PR, do you think it's worth to merge it or we need to rebase it?

**Comment by sandygudie** [comment]
Hi Batool,
let's merge, the issue is still there https://oscsa-en-blog.netlify.app/posts/sandy-richie-everyone-struggles/

**Comment by sandygudie** [comment]
Let me pull the update to be sure.

**Comment by sandygudie** [comment]
@BatoolMM  it's good for merging now,

**Review by BatoolMM — APPROVED** [review]

**Pull request merged**
