### PR TITLE
fix pr template.md file

### PR DESCRIPTION
**Pull request by sandygudie**
Fixes: https://github.com/Open-Science-Community-Saudi-Arabia/OSCSA-en-blog/issues/43

PR Description:
- Fix the existing PR template file by removing repeated citation metadata on the index.qmd file, the repeated citation metadata throws an error when running the "quarto preview"

### CODE REVIEW

**Comment by sandygudie** [comment]
@BatoolMM @alswajiab @RealRichi3
Please review
the PR has to be merged to see if the template works

**Comment by BatoolMM** [comment]
Hi @sandygudie, I am not sure why you are trying to remove `citation:`. Can you add more description in your PR!

**Comment by sandygudie** [comment]
> Hi @sandygudie, I am not sure why you are trying to remove `citation:`. Can you add more description in your PR!

i did not remove it, it's repeated

**Review by BatoolMM — APPROVED** [review]
OK, I see now!
Can you also make sure to use tags for any PR or issue you open, please?

**Comment by BatoolMM** [comment]
Feel free to merge now!

**Comment by sandygudie** [comment]
> Feel free to merge now!
oh! i don't have access to the repository, I don't have merge privilege

**Comment by sandygudie** [comment]
> Feel free to merge now!

oh! i don't have access to the repository, I don't have merge privilege

**Comment by BatoolMM** [comment]
@all-contributors please add @sandygudie for bug fix

**Pull request merged**
